language: julia
os:
  - linux
  - osx
  - windows
arch:
  - amd64
  - arm64
julia:
  - 1.7.2
matrix:
  exclude:
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
